-- Generated by `.github/scripts/generate.py` from `pets/`. Do not edit by hand.
local _, Addon = ...
if not Addon.IS_TBC then return end
Addon:MergeTameableAbilities({
  ["bite"] = {
    ["learned_by"] = {
      "Bat",
      "Bear",
      "Boar",
      "Carrion Bird",
      "Cat",
      "Crocolisk",
      "Dragonhawk",
      "Gorilla",
      "Hyena",
      "Nether Ray",
      "Raptor",
      "Ravager",
      "Serpent",
      "Spider",
      "Tallstrider",
      "Turtle",
      "Warp Stalker",
      "Wind Serpent",
      "Wolf"
    }
  },
  ["claw"] = {
    ["learned_by"] = {
      "Bear",
      "Carrion Bird",
      "Cat",
      "Crab",
      "Owl",
      "Raptor",
      "Scorpid",
      "Warp Stalker"
    }
  },
  ["dash"] = {
    ["learned_by"] = {
      "Boar",
      "Cat",
      "Hyena",
      "Raptor",
      "Ravager",
      "Tallstrider",
      "Wolf"
    }
  },
  ["dive"] = {
    ["learned_by"] = {
      "Bat",
      "Carrion Bird",
      "Dragonhawk",
      "Nether Ray",
      "Owl",
      "Wind Serpent"
    }
  },
  ["firebreath"] = {
    ["name"] = "Fire Breath",
    ["learned_by"] = {
      "Dragonhawk"
    },
    ["ranks"] = {
      {
        ["rank"] = 1,
        ["spell_id"] = 34889,
        ["pet_level"] = 1,
        ["training_cost"] = 5
      },
      {
        ["rank"] = 2,
        ["spell_id"] = 35323,
        ["pet_level"] = 60,
        ["training_cost"] = 25
      }
    }
  },
  ["gore"] = {
    ["name"] = "Gore",
    ["learned_by"] = {
      "Boar",
      "Ravager"
    },
    ["ranks"] = {
      {
        ["rank"] = 1,
        ["spell_id"] = 35290,
        ["pet_level"] = 1,
        ["training_cost"] = 1
      },
      {
        ["rank"] = 2,
        ["spell_id"] = 35291,
        ["pet_level"] = 8,
        ["training_cost"] = 4
      },
      {
        ["rank"] = 3,
        ["spell_id"] = 35292,
        ["pet_level"] = 16,
        ["training_cost"] = 7
      },
      {
        ["rank"] = 4,
        ["spell_id"] = 35293,
        ["pet_level"] = 24,
        ["training_cost"] = 10
      },
      {
        ["rank"] = 5,
        ["spell_id"] = 35294,
        ["pet_level"] = 32,
        ["training_cost"] = 13
      },
      {
        ["rank"] = 6,
        ["spell_id"] = 35295,
        ["pet_level"] = 40,
        ["training_cost"] = 17
      },
      {
        ["rank"] = 7,
        ["spell_id"] = 35296,
        ["pet_level"] = 48,
        ["training_cost"] = 21
      },
      {
        ["rank"] = 8,
        ["spell_id"] = 35297,
        ["pet_level"] = 56,
        ["training_cost"] = 25
      },
      {
        ["rank"] = 9,
        ["spell_id"] = 35298,
        ["pet_level"] = 63,
        ["training_cost"] = 29
      }
    }
  },
  ["poisonspit"] = {
    ["name"] = "Poison Spit",
    ["learned_by"] = {
      "Serpent"
    },
    ["ranks"] = {
      {
        ["rank"] = 1,
        ["spell_id"] = 35387,
        ["pet_level"] = 15,
        ["training_cost"] = 5
      },
      {
        ["rank"] = 2,
        ["spell_id"] = 35389,
        ["pet_level"] = 45,
        ["training_cost"] = 20
      },
      {
        ["rank"] = 3,
        ["spell_id"] = 35392,
        ["pet_level"] = 60,
        ["training_cost"] = 25
      }
    }
  },
  ["warp"] = {
    ["name"] = "Warp",
    ["learned_by"] = {
      "Warp Stalker"
    },
    ["ranks"] = {
      {
        ["rank"] = 1,
        ["spell_id"] = 35346,
        ["pet_level"] = 60,
        ["training_cost"] = 1
      }
    }
  }
})
