name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Regenerate Data
        run: python3 .github/scripts/generate.py
      - name: Git Diff on Data
        run: git diff --exit-code src/data/
